"""Workflow & Dependencies service.

Same module pipeline shape as the rest. Workflow synthesises the upstream
analyses (visa, documents, family, finance, job-fit, country-comparison)
into a directed task graph. The graph is generated by the LLM but the
service performs structural validation in a post-AI step:

  - Every edge endpoint must reference a declared node id.
  - The current_stage_node_id must reference a declared node id.
  - Every entry in critical_path must reference a declared node id.
  - blocked_node_ids must match status="blocked" nodes (we only enforce a
    subset relationship to give the model some headroom).
  - The graph must be a DAG (no cycles).

If structural validation fails we treat it the same as schema validation
failure — surface a failed envelope so the frontend can render the failed
state cleanly.
"""

from __future__ import annotations

import time
from datetime import datetime, timezone
from typing import Any

from pydantic import BaseModel, Field
from sqlalchemy.ext.asyncio import AsyncSession

from app.ai.gateway import AIGateway, GenerationRequest, get_ai_gateway
from app.ai.telemetry import DBSink
from app.ai.types import (
    ModelTier,
    ProviderError,
    SchemaValidationFailed,
)
from app.config import get_settings
from app.middleware.error_handler import BadRequest, Forbidden, NotFound
from app.modules.case.repository import CaseRepository
from app.modules.profile.repository import ProfileRepository
from app.modules.profile.service import ProfileService
from app.modules.resume.repository import ResumeRepository
from app.modules.workflow.repository import WorkflowRepository
from app.modules.workflow.schemas import (
    WorkflowDetail,
    WorkflowInputs,
)
from app.observability import log_error, log_event
from app.schemas.envelope import (
    AnalysisEnvelope,
    AnalysisKind,
    AnalysisStatus,
    Assumption,
    EnvelopeMetadata,
    NextAction,
    Risk,
)
from app.schemas.profile import UserProfile
from app.storage.analyses import AnalysesRepository, stable_input_hash

KIND = AnalysisKind.WORKFLOW.value


class _ModelEnvelope(BaseModel):
    status: AnalysisStatus
    score: int = Field(ge=0, le=100)
    summary: str
    reasoning: str
    risks: list[Risk] = Field(default_factory=list)
    next_actions: list[NextAction] = Field(default_factory=list)
    confidence: float = Field(ge=0.0, le=1.0)
    assumptions: list[Assumption]
    detail: WorkflowDetail


class WorkflowService:
    PROMPT_NAME = "workflow"
    PROMPT_VERSION = "v1"

    def __init__(
        self,
        session: AsyncSession,
        *,
        gateway: AIGateway | None = None,
    ) -> None:
        self.session = session
        self.repo = WorkflowRepository(session)
        self.profiles = ProfileService(ProfileRepository(session))
        self.resumes = ResumeRepository(session)
        self.cases = CaseRepository(session)
        if gateway is None:
            base = get_ai_gateway()
            gateway = AIGateway(provider=base.provider, telemetry=DBSink(session))
        self.gateway = gateway
        self._settings = get_settings()

    # ----- read APIs -----

    async def latest(self, *, user_id: str, case_id: str) -> dict | None:
        await self._authz_case(user_id=user_id, case_id=case_id)
        row = await self.repo.latest(case_id)
        return _row_to_response(row)

    async def history(
        self, *, user_id: str, case_id: str, limit: int = 20
    ) -> list[dict]:
        await self._authz_case(user_id=user_id, case_id=case_id)
        rows = await self.repo.history(case_id, limit=limit)
        return [_row_to_response(r) for r in rows if r is not None]  # type: ignore[list-item]

    # ----- generate -----

    async def run(
        self,
        *,
        user_id: str,
        case_id: str,
        body: WorkflowInputs,
    ) -> dict:
        case = await self._authz_case(user_id=user_id, case_id=case_id)
        profile = await self.profiles.get_profile(user_id)

        merged_inputs = _build_inputs(
            profile=profile, case_inputs=case.inputs_snapshot or {}
        )
        if not merged_inputs.get("target_country"):
            raise BadRequest(
                "workflow requires target_country on the profile."
            )

        resume = await self.resumes.latest_for_user(user_id)
        resume_extracted = (
            resume.extracted_json if resume and resume.extracted_json else None
        )
        prior = await _prior_analyses_summary(self.session, case_id)

        input_payload = {
            "profile": profile.model_dump(mode="json"),
            "resume_extraction": resume_extracted or {},
            "case_inputs": merged_inputs,
            "prior_analyses": prior,
        }
        natural_hash = stable_input_hash(input_payload)

        if not body.force:
            cached = await self.repo.find_cached(case_id, natural_hash)
            if cached is not None and cached.status == "ready":
                log_event(
                    "workflow.cache_hit",
                    case_id=case_id,
                    user_id=user_id,
                    module_name="workflow-dependencies",
                    input_hash=natural_hash,
                    analysis_version=cached.analysis_version,
                )
                return _row_to_response(cached)  # type: ignore[return-value]

        previous = await self.repo.latest(case_id)
        version = await self.repo.next_version(case_id)
        input_hash = (
            stable_input_hash({"_natural": natural_hash, "_force_version": version})
            if body.force
            else natural_hash
        )
        # Workflow synthesis is reasoning-heavy — use the smarter tier.
        model = self._settings.reasoning_model
        prompt_version = self.PROMPT_VERSION

        log_event(
            "workflow.run_start",
            case_id=case_id,
            user_id=user_id,
            module_name="workflow-dependencies",
            input_hash=input_hash,
            analysis_version=version,
            prompt_version=prompt_version,
            model=model,
        )
        row = await self.repo.create_generating(
            case_id=case_id,
            input_hash=input_hash,
            analysis_version=version,
            inputs_revision_at_gen=case.inputs_revision,
            model=model,
            prompt_version=prompt_version,
        )

        started = time.perf_counter()
        try:
            req = GenerationRequest(
                kind=KIND,
                prompt_name=self.PROMPT_NAME,
                prompt_version=self.PROMPT_VERSION,
                model_tier=ModelTier.REASONING,
                schema=_ModelEnvelope,
                system="Return one JSON object that satisfies the schema.",
                user=_render_user_message(input_payload),
                case_id=case_id,
                metadata={"user_id": user_id},
            )
            result = await self.gateway.generate(req)

        except SchemaValidationFailed:
            return await _record_failure(
                repo=self.repo,
                row_id=row.id,
                started=started,
                input_hash=input_hash,
                version=version,
                model=model,
                prompt_version=prompt_version,
                case_id=case_id,
                user_id=user_id,
                error_code="schema_validation_failed",
                user_message="The AI response failed validation after retries. Please try again.",
            )
        except ProviderError as e:
            return await _record_failure(
                repo=self.repo,
                row_id=row.id,
                started=started,
                input_hash=input_hash,
                version=version,
                model=model,
                prompt_version=prompt_version,
                case_id=case_id,
                user_id=user_id,
                error_code="provider_error",
                user_message="The AI provider is unavailable right now. Please try again shortly.",
                extra={"detail": str(e)[:240]},
            )

        # Structural integrity check on the graph itself.
        struct_error = _validate_graph(result.parsed.detail)
        if struct_error:
            return await _record_failure(
                repo=self.repo,
                row_id=row.id,
                started=started,
                input_hash=input_hash,
                version=version,
                model=model,
                prompt_version=prompt_version,
                case_id=case_id,
                user_id=user_id,
                error_code="graph_validation_failed",
                user_message="The AI returned an inconsistent workflow graph. Please try again.",
                extra={"reason": struct_error},
            )

        latency_ms = result.metrics.latency_ms or int(
            (time.perf_counter() - started) * 1000
        )
        full_envelope = _assemble_envelope(
            model_envelope=result.parsed,
            input_hash=input_hash,
            version=version,
            model=model,
            prompt_version=prompt_version,
            tokens_in=result.metrics.tokens_in,
            tokens_out=result.metrics.tokens_out,
            latency_ms=latency_ms,
        )
        await self.repo.mark_ready(
            analysis_id=row.id,
            envelope=full_envelope,
            tokens_in=result.metrics.tokens_in,
            tokens_out=result.metrics.tokens_out,
            latency_ms=latency_ms,
            cost_usd=result.metrics.cost_usd,
        )
        if previous is not None and previous.id != row.id:
            await self.repo.supersede(old_id=previous.id, new_id=row.id)

        log_event(
            "workflow.run_success",
            case_id=case_id,
            user_id=user_id,
            module_name="workflow-dependencies",
            input_hash=input_hash,
            analysis_version=version,
            prompt_version=prompt_version,
            model=model,
            status="ready",
            stale=False,
            recompute_required=False,
            latency_ms=latency_ms,
            tokens_in=result.metrics.tokens_in,
            tokens_out=result.metrics.tokens_out,
            cost_usd=result.metrics.cost_usd,
            confidence=full_envelope.get("confidence"),
        )

        return {
            "id": row.id,
            "case_id": case_id,
            "kind": KIND,
            "status": "ready",
            "envelope": full_envelope,
            "analysis_version": version,
            "stale": False,
            "recompute_required": False,
            "stale_reason": None,
            "cached": False,
        }

    # ----- helpers -----

    async def _authz_case(self, *, user_id: str, case_id: str):
        row = await self.cases.get_by_id(case_id)
        if row is None:
            raise NotFound("case not found")
        if row.user_id != user_id:
            raise Forbidden("not your case")
        return row


# ---- pure helpers ----


def _build_inputs(*, profile: UserProfile, case_inputs: dict) -> dict[str, Any]:
    out = {
        "target_country": profile.target_country,
        "target_city": profile.target_city,
        "current_country": profile.current_country,
        "nationality": profile.nationality,
        "current_visa_status": profile.current_visa_status,
        "needs_visa_sponsorship": profile.needs_visa_sponsorship,
        "move_urgency": profile.move_urgency,
        "current_role": profile.current_role,
        "industry": profile.industry,
        "years_experience": profile.years_experience,
        "current_document_status": profile.current_document_status or {},
    }
    return out


async def _prior_analyses_summary(session: AsyncSession, case_id: str) -> list[dict]:
    repo = AnalysesRepository(session)
    rows = await repo.list_all_for_case(case_id)
    out: list[dict] = []
    for r in rows:
        if r.kind == KIND or not r.envelope:
            continue
        env = r.envelope
        out.append(
            {
                "kind": r.kind,
                "score": env.get("score"),
                "summary": (env.get("summary") or "")[:240],
                "confidence": env.get("confidence"),
            }
        )
    return out


def _render_user_message(payload: dict) -> str:
    import json as _json

    return _json.dumps(payload, sort_keys=True, default=str)


def _validate_graph(detail: WorkflowDetail) -> str | None:
    """Structural integrity checks on the workflow graph.

    Returns the first error message found, or None if the graph is valid.
    """
    node_ids = {n.id for n in detail.nodes}
    if len(node_ids) != len(detail.nodes):
        return "duplicate node ids"

    for e in detail.edges:
        if e.from_node not in node_ids:
            return f"edge from_node {e.from_node!r} is not a declared node"
        if e.to_node not in node_ids:
            return f"edge to_node {e.to_node!r} is not a declared node"
        if e.from_node == e.to_node:
            return f"self-loop on node {e.from_node!r}"

    if detail.current_stage_node_id not in node_ids:
        return f"current_stage_node_id {detail.current_stage_node_id!r} is not a declared node"

    for nid in detail.critical_path:
        if nid not in node_ids:
            return f"critical_path entry {nid!r} is not a declared node"

    for nid in detail.blocked_node_ids:
        if nid not in node_ids:
            return f"blocked_node_ids entry {nid!r} is not a declared node"

    # blocked nodes listed in blocked_node_ids must all carry status="blocked"
    blocked_set = set(detail.blocked_node_ids)
    for n in detail.nodes:
        if n.id in blocked_set and n.status != "blocked":
            return f"node {n.id!r} is in blocked_node_ids but status is {n.status!r}"

    # Cycle check (DAG): Kahn's algorithm.
    indeg: dict[str, int] = {nid: 0 for nid in node_ids}
    adj: dict[str, list[str]] = {nid: [] for nid in node_ids}
    for e in detail.edges:
        adj[e.from_node].append(e.to_node)
        indeg[e.to_node] += 1
    queue = [n for n, d in indeg.items() if d == 0]
    visited = 0
    while queue:
        cur = queue.pop()
        visited += 1
        for nxt in adj[cur]:
            indeg[nxt] -= 1
            if indeg[nxt] == 0:
                queue.append(nxt)
    if visited != len(node_ids):
        return "graph contains a cycle"

    # Duration sanity per node
    for n in detail.nodes:
        if n.estimated_duration_days_min > n.estimated_duration_days_max:
            return f"node {n.id!r}: duration min > max"

    # Total range sanity
    if detail.total_estimated_days_min > detail.total_estimated_days_max:
        return "total_estimated_days_min > total_estimated_days_max"

    return None


def _assemble_envelope(
    *,
    model_envelope: _ModelEnvelope,
    input_hash: str,
    version: int,
    model: str,
    prompt_version: str,
    tokens_in: int | None,
    tokens_out: int | None,
    latency_ms: int | None,
) -> dict:
    metadata = EnvelopeMetadata(
        generated_at=datetime.now(timezone.utc),
        model=model,
        prompt_version=prompt_version,
        tokens_in=tokens_in,
        tokens_out=tokens_out,
        latency_ms=latency_ms,
    )
    full = AnalysisEnvelope[WorkflowDetail](
        status=model_envelope.status,
        score=model_envelope.score,
        summary=model_envelope.summary,
        reasoning=model_envelope.reasoning,
        risks=model_envelope.risks,
        next_actions=model_envelope.next_actions,
        confidence=model_envelope.confidence,
        metadata=metadata,
        detail=model_envelope.detail,
        analysis_version=version,
        stale=False,
        recompute_required=False,
        stale_reason=None,
        input_hash=input_hash,
        assumptions=model_envelope.assumptions,
    )
    return full.model_dump(mode="json")


async def _record_failure(
    *,
    repo: WorkflowRepository,
    row_id: str,
    started: float,
    input_hash: str,
    version: int,
    model: str,
    prompt_version: str,
    case_id: str,
    user_id: str,
    error_code: str,
    user_message: str,
    extra: dict | None = None,
) -> dict:
    latency_ms = int((time.perf_counter() - started) * 1000)
    envelope = _failed_envelope(
        input_hash=input_hash,
        version=version,
        model=model,
        prompt_version=prompt_version,
        error_code=error_code,
        user_message=user_message,
        extra=extra,
    )
    await repo.mark_failed(
        analysis_id=row_id, error_envelope=envelope, latency_ms=latency_ms
    )
    log_error(
        "workflow.run_failed",
        case_id=case_id,
        user_id=user_id,
        module_name="workflow-dependencies",
        input_hash=input_hash,
        analysis_version=version,
        prompt_version=prompt_version,
        model=model,
        status="failed",
        error_code=error_code,
        latency_ms=latency_ms,
    )
    return {
        "id": row_id,
        "case_id": case_id,
        "kind": KIND,
        "status": "failed",
        "envelope": envelope,
        "analysis_version": version,
        "stale": False,
        "recompute_required": False,
        "stale_reason": None,
    }


def _failed_envelope(
    *,
    input_hash: str,
    version: int,
    model: str,
    prompt_version: str,
    error_code: str,
    user_message: str,
    extra: dict | None = None,
) -> dict:
    return {
        "status": "failed",
        "kind": KIND,
        "error_code": error_code,
        "user_message": user_message,
        "metadata": {
            "model": model,
            "prompt_version": prompt_version,
            "input_hash": input_hash,
            "analysis_version": version,
            **(extra or {}),
        },
    }


def _row_to_response(row) -> dict | None:
    if row is None:
        return None
    return {
        "id": row.id,
        "case_id": row.case_id,
        "kind": row.kind,
        "status": row.status,
        "envelope": row.envelope,
        "analysis_version": row.analysis_version,
        "stale": row.stale,
        "recompute_required": row.recompute_required,
        "stale_reason": row.stale_reason,
        "model": row.model,
        "prompt_version": row.prompt_version,
        "input_hash": row.input_hash,
        "tokens_in": row.tokens_in,
        "tokens_out": row.tokens_out,
        "latency_ms": row.latency_ms,
        "created_at": row.created_at,
        "updated_at": row.updated_at,
    }
